#ifndef __GUIMainWindow__
#define __GUIMainWindow__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#pragma comment(lib, "FreeImage")

#define  FREEIMAGE_LIB
#define PI 3.1415

#include <wx/colourdata.h>
#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/msgdlg.h>
#include <wx/dcbuffer.h>
#include <wx/colordlg.h>
#include <math.h>
#include "CImg.h"
#include "FreeImage.h"

/** Implementing MainWindow */
class GUIMainWindow : public MainWindow
{
protected:

	// Handlers for MainWindow events.
	void windowOnSize(wxSizeEvent& event);
	void windowUIUpdated(wxUpdateUIEvent& event);
	void m_loadImage(wxCommandEvent& event);
	void m_censore(wxCommandEvent& event);
	void m_erode(wxCommandEvent& event);
	void m_animate(wxCommandEvent& event);

public:
	/** Constructor */
	GUIMainWindow(wxWindow* parent);
	//// end generated class members

	//ROZMIARY OKNA
	int WIDTH;
	int HEIGHT;

	//OBRAZEK ORYGINALNY
	wxImage initImage;

	//OBRAZEK SKOPIOWANY
	wxImage copyImage;

	//FLAGA Z KTOREJ BEDZIEMY KORZYSTAC DO ANIMOWANIA
	bool ANIMATE;

	//BITMAPA Z BIBLIOTEKI FREEIMAGE
	FIBITMAP* bitmap;

	//FUNKCJA SLUZACA DO RYSOWANIA CALOSCI NA EKRAN + POZNIEJ DO UPDATE'OWANIA W TRAKCIE DZIALANIA
	void draw();

};

#endif // __GUIMainWindow__
