#ifndef __GUIMainFrame__
#define __GUIMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/colordlg.h> //color dialog ktory pozwala nam wybrac kolor gwiazdki
#include <wx/dcclient.h> //dcclient pozwala nam na rysowanie na panelu
#include <wx/dcbuffer.h> //podwojne buforowanie, lekarstwo na flickering
#include <wx/filedlg.h> //file dialog - pozwala na zapisywanie pliku przez okno dialogowe (uzyskiwanie lokalizacji)
#include <wx/log.h> //log pozwala na wyswietlenie bledu
#include <wx/wfstream.h> //do sytuacji gdy lokalizacja nie jest prawidlowa, daje informacje zeby wyswietlic komunikat o bledzie

/** Implementing MainFrame */
class GUIMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void funcOnSizeUpdate( wxSizeEvent& event );
		void funcOnUpUI( wxUpdateUIEvent& event );
		void funcSaveImage( wxCommandEvent& event );
		void funcShowBanan( wxCommandEvent& event );
		void funcScrollSlider( wxScrollEvent& event );
		void funcChangeColor( wxCommandEvent& event );
		void funcUpdateText( wxCommandEvent& event );
		void changeSymbol( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMainFrame( wxWindow* parent );
	//// end generated class members
		void paintOnPanel(wxClientDC& dcClient);
		void drawText(wxBufferedDC& bufferedPanel, wxString _text);
		void drawMonkey(wxBufferedDC& bufferedPanel);
		void drawStar(wxBufferedDC& bufferedPanel, wxColour _colour);
		void drawMoon(wxBufferedDC& bufferedPanel);
		void drawSun(wxBufferedDC& bufferedPanel);
		void declareStarPosition(wxPoint* symbolPosition);
		void setHandPos();
		
	private:
		//wartoœci wspó³rzêdnych œrodka panelu drawingPanel
		int dPx;
		int dPy;
		
		//wspó³rzêdne drugiego punktu prawej reki malpki
		int xH;
		int yH;

		bool _bananaActive; //flaga okreslajaca czy banan jest aktywny
		double _position; //pozycja scrollbara
		wxBitmap _banana; //bitmap ktory tworzymy z png banana
		wxBitmap _panelPicture; //bitmapa z ktorej zapisujemy do pliku obrazek na panelu
		wxImage _panelImage; //image do ktorego przerabiamy bitmape zeby ja zapisac
		wxColour _colour; //kolor gwiazdki
		wxString _text; //tekst ktory bedzie napisany w dwoch textboxach
		wxString _chosenSymbol; //przechowuje symbol wybrany w symbolChooser

};

#endif // __GUIMainFrame__
